list= ['toyota','honda','nissan','bmw']
print("length of list is", len(list))
print("first element is",list[0])
print ("last element is",list[-1])
list.append('bmw')
print('updated list',list)
list.remove('honda')
print('updated list',list)
list.sort()
print('sorted list ',list)
list.pop(1)
print('updated list after popping list 1',list)
list.reverse()
print('updated list after reversing',list)
print('multiplication on list:',list*4)
list.clear()
print('list after clearing',list)